
CREATE TABLE `user` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(320) NOT NULL,
  `MAIL` varchar(320) NOT NULL,
  `PASSWORD` varchar(128) NULL,
  `ROLES` varchar(128) NOT NULL,
  PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `ecole` (
  `CODEECOLE` int(11) NOT NULL,
  PRIMARY KEY (`CODEECOLE`)
)

CREATE TABLE `intervenant` (
  `ID` int(11) NOT NULL,
  `NOM` varchar(320 NOT NULL,
)

CREATE TABLE `produit` (
  `ID` int(11) NOT NULL,

)

-- CREATE TABLE `PDV` (

-- )
-- CREATE TABLE `EMPOCHAGE` (

-- )
-- CREATE TABLE `OUTPOST` (

-- )
-- CREATE TABLE `LIVRAISON` (

-- )
-- CREATE TABLE `FACTURE` (

-- )
-- CREATE TABLE `PDV` (

-- )
-- CREATE TABLE `EMPOCHAGE` (

-- )
-- CREATE TABLE `OUTPOST` (

-- )
-- CREATE TABLE `LIVRAISON` (

-- )
-- CREATE TABLE `FACTURE` (

-- )